name: build

on:
  push:
    branches:
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
        id: go

      - name: checkout
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: build
        run: |
          make build
          build/hub --version
          build/hub s --help

